syntax on
filetype plugin indent on
set autoindent
set expandtab
set tabstop=4
set shiftwidth=4
set backspace=2
set foldmethod=syntax
colorscheme murphy
packloadall
silent! helptags ALL
set fileformat=unix
set fileformats=unix,dos

function! s:set_fileformat()
    try
        setlocala fileformat=unix
    catch
    endtry
endfunction
autocmd BufRead * :call <SID>set_fileformat()

